import AsyncStorage from '@react-native-async-storage/async-storage';
import _ from 'lodash';
import moment from 'moment';
import {useEffect, useState} from 'react';

const theme1 = require('../assets/images/theme/1.png');
const theme2 = require('../assets/images/theme/2.png');
const theme3 = require('../assets/images/theme/3.png');
const theme4 = require('../assets/images/theme/4.png');
const theme5 = require('../assets/images/theme/5.png');
const theme6 = require('../assets/images/theme/6.png');
const theme7 = require('../assets/images/theme/7.png');
const theme8 = require('../assets/images/theme/8.png');
const theme9 = require('../assets/images/theme/9.png');
const theme10 = require('../assets/images/theme/10.png');
const theme11 = require('../assets/images/theme/11.png');
const theme12 = require('../assets/images/theme/12.png');
const theme13 = require('../assets/images/theme/13.png');
const theme14 = require('../assets/images/theme/14.png');
const theme15 = require('../assets/images/theme/15.png');
const theme16 = require('../assets/images/theme/16.png');
const theme17 = require('../assets/images/theme/17.png');
const theme18 = require('../assets/images/theme/18.png');
const theme19 = require('../assets/images/theme/19.png');
const theme20 = require('../assets/images/theme/20.png');
const theme21 = require('../assets/images/theme/21.png');
const theme22 = require('../assets/images/theme/22.png');
const theme23 = require('../assets/images/theme/23.png');
const theme24 = require('../assets/images/theme/24.png');
const theme25 = require('../assets/images/theme/25.png');
const theme26 = require('../assets/images/theme/26.png');
const theme27 = require('../assets/images/theme/27.png');
const theme28 = require('../assets/images/theme/28.png');
const theme29 = require('../assets/images/theme/29.png');
const theme30 = require('../assets/images/theme/30.png');
const theme31 = require('../assets/images/theme/31.png');
const theme32 = require('../assets/images/theme/32.png');
const theme33 = require('../assets/images/theme/33.png');
const theme34 = require('../assets/images/theme/34.png');
const theme35 = require('../assets/images/theme/35.png');
const theme36 = require('../assets/images/theme/36.png');
const theme37 = require('../assets/images/theme/37.png');
const theme38 = require('../assets/images/theme/38.png');
const theme39 = require('../assets/images/theme/39.png');
const theme40 = require('../assets/images/theme/40.png');

export const listTheme = [
  {
    id: 1,
    entry_id: null,
    name: 'Theme 1',
    flag: null,
    is_free: 0,
    font_family: 'EBGaramond-Medium',
    font_size: 18,
    line_height: 24,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2022-11-17T08:35:00.000000Z',
    updated_at: null,
    imgLocal: theme1,
    background: {
      id: 17,
      owner_id: 1,
      type: 'theme',
      name: '1.png',
      created_at: '2022-11-17T08:35:00.000000Z',
      updated_at: null,
    },
  },
  {
    id: 2,
    entry_id: null,
    name: 'Theme 2',
    flag: null,
    is_free: 0,
    font_family: 'Koulen-Regular',
    font_size: 18,
    line_height: 24,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2022-11-17T08:35:00.000000Z',
    updated_at: null,
    imgLocal: theme2,
    background: {
      id: 18,
      owner_id: 2,
      type: 'theme',
      name: '2.png',
      created_at: '2022-11-17T08:35:00.000000Z',
      updated_at: null,
    },
  },
  {
    id: 3,
    entry_id: null,
    name: 'Theme 3',
    flag: null,
    is_free: 0,
    font_family: 'FjallaOne-Regular',
    font_size: 18,
    line_height: 24,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2022-11-17T08:35:00.000000Z',
    updated_at: null,
    imgLocal: theme3,
    background: {
      id: 19,
      owner_id: 3,
      type: 'theme',
      name: '3.png',
      created_at: '2022-11-17T08:35:00.000000Z',
      updated_at: null,
    },
  },
  {
    id: 4,
    entry_id: null,
    name: 'Theme 4',
    flag: null,
    is_free: 0,
    font_family: 'Montserrat-SemiBold',
    font_size: 18,
    line_height: 24,
    text_color: '#FFDA97',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2022-11-17T08:35:00.000000Z',
    updated_at: null,
    imgLocal: theme4,
    background: {
      id: 20,
      owner_id: 4,
      type: 'theme',
      name: '4.png',
      created_at: '2022-11-17T08:35:00.000000Z',
      updated_at: null,
    },
  },
  {
    id: 5,
    entry_id: null,
    name: 'Theme 5',
    flag: null,
    is_free: 0,
    font_family: 'PatuaOne-Regular',
    font_size: 18,
    line_height: 24,
    text_color: '#FFFFFF',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: 'rgba(0,0,0,0.7)',
    bg_image_color: null,
    status: 2,
    created_at: '2022-11-17T08:35:00.000000Z',
    updated_at: null,
    imgLocal: theme5,
    background: {
      id: 21,
      owner_id: 5,
      type: 'theme',
      name: '5.png',
      created_at: '2022-11-17T08:35:00.000000Z',
      updated_at: null,
    },
  },
  {
    id: 7,
    entry_id: null,
    name: 'Theme 7',
    flag: null,
    is_free: 0,
    font_family: 'Fondamento-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme7,
    background: {
      id: 57,
      owner_id: 7,
      type: 'theme',
      name: '7.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 8,
    entry_id: null,
    name: 'Theme 8',
    flag: null,
    is_free: 0,
    font_family: 'AnticDidone-Regular',
    font_size: 22,
    line_height: 32,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme8,
    background: {
      id: 58,
      owner_id: 8,
      type: 'theme',
      name: '8.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 9,
    entry_id: null,
    name: 'Theme 9',
    flag: null,
    is_free: 0,
    font_family: 'BethEllen-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme9,
    background: {
      id: 59,
      owner_id: 9,
      type: 'theme',
      name: '9.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 10,
    entry_id: null,
    name: 'Theme 10',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme10,
    background: {
      id: 60,
      owner_id: 10,
      type: 'theme',
      name: '10.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 11,
    entry_id: null,
    name: 'Theme 11',
    flag: null,
    is_free: 0,
    font_family: 'Fondamento-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme11,
    background: {
      id: 61,
      owner_id: 11,
      type: 'theme',
      name: '11.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 12,
    entry_id: null,
    name: 'Theme 12',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme12,
    background: {
      id: 62,
      owner_id: 12,
      type: 'theme',
      name: '12.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 13,
    entry_id: null,
    name: 'Theme 13',
    flag: null,
    is_free: 0,
    font_family: 'CarterOne',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme13,
    background: {
      id: 63,
      owner_id: 13,
      type: 'theme',
      name: '13.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 14,
    entry_id: null,
    name: 'Theme 14',
    flag: null,
    is_free: 0,
    font_family: 'Kreon-Regular',
    font_size: 22,
    line_height: 36,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: 'rgba(0, 0, 0, 0.5)',
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme14,
    background: {
      id: 64,
      owner_id: 14,
      type: 'theme',
      name: '14.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 15,
    entry_id: null,
    name: 'Theme 15',
    flag: null,
    is_free: 0,
    font_family: 'Caveat-Bold',
    font_size: 24,
    line_height: 30,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme15,
    background: {
      id: 65,
      owner_id: 15,
      type: 'theme',
      name: '15.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 16,
    entry_id: null,
    name: 'Theme 16',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme16,
    background: {
      id: 66,
      owner_id: 16,
      type: 'theme',
      name: '16.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 17,
    entry_id: null,
    name: 'Theme 17',
    flag: null,
    is_free: 0,
    font_family: 'DeliusSwashCaps-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme17,
    background: {
      id: 67,
      owner_id: 17,
      type: 'theme',
      name: '17.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 18,
    entry_id: null,
    name: 'Theme 18',
    flag: null,
    is_free: 0,
    font_family: 'Kreon-Regular',
    font_size: 22,
    line_height: 36,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: 'rgba(0, 0, 0, 0.5)',
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme18,
    background: {
      id: 68,
      owner_id: 18,
      type: 'theme',
      name: '18.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 19,
    entry_id: null,
    name: 'Theme 19',
    flag: null,
    is_free: 0,
    font_family: 'Girassol-Regular',
    font_size: 24,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme19,
    background: {
      id: 69,
      owner_id: 19,
      type: 'theme',
      name: '19.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 20,
    entry_id: null,
    name: 'Theme 20',
    flag: null,
    is_free: 0,
    font_family: 'Gaegu-Regular',
    font_size: 26,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme20,
    background: {
      id: 70,
      owner_id: 20,
      type: 'theme',
      name: '20.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 21,
    entry_id: null,
    name: 'Theme 21',
    flag: null,
    is_free: 0,
    font_family: 'Farsan-Regular',
    font_size: 28,
    line_height: 39,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme21,
    background: {
      id: 71,
      owner_id: 21,
      type: 'theme',
      name: '21.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 22,
    entry_id: null,
    name: 'Theme 22',
    flag: null,
    is_free: 0,
    font_family: 'Hoefler Text Black',
    font_size: 26,
    line_height: 39,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme22,
    background: {
      id: 72,
      owner_id: 22,
      type: 'theme',
      name: '22.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 23,
    entry_id: null,
    name: 'Theme 23',
    flag: null,
    is_free: 0,
    font_family: 'IM FELL DW Pica',
    font_size: 26,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme23,
    background: {
      id: 73,
      owner_id: 23,
      type: 'theme',
      name: '23.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 24,
    entry_id: null,
    name: 'Theme 24',
    flag: null,
    is_free: 0,
    font_family: 'IbarraRealNova-Bold',
    font_size: 26,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme24,
    background: {
      id: 74,
      owner_id: 24,
      type: 'theme',
      name: '24.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 25,
    entry_id: null,
    name: 'Theme 25',
    flag: null,
    is_free: 0,
    font_family: 'Iceberg-Regular',
    font_size: 26,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme25,
    background: {
      id: 75,
      owner_id: 25,
      type: 'theme',
      name: '25.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 26,
    entry_id: null,
    name: 'Theme 26',
    flag: null,
    is_free: 0,
    font_family: 'PlayfairDisplay-Bold',
    font_size: 26,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme26,
    background: {
      id: 76,
      owner_id: 26,
      type: 'theme',
      name: '26.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 27,
    entry_id: null,
    name: 'Theme 27',
    flag: null,
    is_free: 0,
    font_family: 'Rowdies-Regular',
    font_size: 26,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme27,
    background: {
      id: 77,
      owner_id: 27,
      type: 'theme',
      name: '27.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 28,
    entry_id: null,
    name: 'Theme 28',
    flag: null,
    is_free: 0,
    font_family: 'Merienda-Bold',
    font_size: 24,
    line_height: 38,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme28,
    background: {
      id: 78,
      owner_id: 28,
      type: 'theme',
      name: '28.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 29,
    entry_id: null,
    name: 'Theme 29',
    flag: null,
    is_free: 0,
    font_family: 'Gloria Hallelujah',
    font_size: 24,
    line_height: 38,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme29,
    background: {
      id: 78,
      owner_id: 29,
      type: 'theme',
      name: '29.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 30,
    entry_id: null,
    name: 'Theme 30',
    flag: null,
    is_free: 0,
    font_family: 'Optima',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme30,
    background: {
      id: 78,
      owner_id: 30,
      type: 'theme',
      name: '30.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 31,
    entry_id: null,
    name: 'Theme 31',
    flag: null,
    is_free: 0,
    font_family: 'PalatinoLTPro-Medium',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme31,
    background: {
      id: 78,
      owner_id: 31,
      type: 'theme',
      name: '31.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 32,
    entry_id: null,
    name: 'Theme 32',
    flag: null,
    is_free: 0,
    font_family: 'Hoefler Text Black',
    font_size: 24,
    line_height: 39,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme32,
    background: {
      id: 78,
      owner_id: 32,
      type: 'theme',
      name: '32.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 33,
    entry_id: null,
    name: 'Theme 33',
    flag: null,
    is_free: 0,
    font_family: 'IM FELL DW Pica',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme33,
    background: {
      id: 78,
      owner_id: 33,
      type: 'theme',
      name: '33.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 34,
    entry_id: null,
    name: 'Theme 34',
    flag: null,
    is_free: 0,
    font_family: 'PalatinoLTPro-Medium',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme34,
    background: {
      id: 78,
      owner_id: 34,
      type: 'theme',
      name: '34.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 35,
    entry_id: null,
    name: 'Theme 35',
    flag: null,
    is_free: 0,
    font_family: 'AnticDidone-Regular',
    font_size: 22,
    line_height: 36,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme35,
    background: {
      id: 78,
      owner_id: 35,
      type: 'theme',
      name: '34.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 36,
    entry_id: null,
    name: 'Theme 36',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 22,
    line_height: 36,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme36,
    background: {
      id: 78,
      owner_id: 36,
      type: 'theme',
      name: '36.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 37,
    entry_id: null,
    name: 'Theme 37',
    flag: null,
    is_free: 0,
    font_family: 'Capriola-Regular',
    font_size: 22,
    line_height: 38,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme37,
    background: {
      id: 78,
      owner_id: 37,
      type: 'theme',
      name: '37.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 38,
    entry_id: null,
    name: 'Theme 38',
    flag: null,
    is_free: 0,
    font_family: 'AnticDidone-Regular',
    font_size: 22,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme38,
    background: {
      id: 78,
      owner_id: 38,
      type: 'theme',
      name: '38.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 39,
    entry_id: null,
    name: 'Theme 39',
    flag: null,
    is_free: 0,
    font_family: 'AnticDidone-Regular',
    font_size: 22,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme39,
    background: {
      id: 78,
      owner_id: 39,
      type: 'theme',
      name: '39.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 40,
    entry_id: null,
    name: 'Theme 40',
    flag: null,
    is_free: 0,
    font_family: 'Gaegu-Regular',
    font_size: 26,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme40,
    background: {
      id: 70,
      owner_id: 40,
      type: 'theme',
      name: '40.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
];

export const useBackgroundQuotes = userThemes => {
  const [themeUser, setThemeUser] = useState(userThemes);

  const shuffleThemes = async themeId => {
    const filterThemes = themeId
      ? listTheme.filter(item => item.id !== themeId)
      : listTheme;
    const getItems =
      filterThemes[Math.floor(Math.random() * filterThemes.length)];
    const updateObj = {
      ...getItems,
      set_date: moment().format('YYYY-MM-DD'),
    };
    const objString = JSON.stringify(updateObj);
    setThemeUser(getItems);
    await AsyncStorage.setItem('randomThemes', objString);
  };

  // console.log('User theme :', themeUser);
  // console.log('User userThemes :', userThemes);

  const getListTheme = () => {
    if (themeUser && themeUser.id) {
      const findTheme = listTheme.find(item => item.id === themeUser.id);
      if (findTheme) {
        return [findTheme];
      }
    }
    return [userThemes];
  };

  useEffect(() => {
    const getThemes = async () => {
      if (userThemes.id === 6) {
        const currentDate = moment().format('YYYY-MM-DD');
        const currentRandomThemes = await AsyncStorage.getItem('randomThemes');
        const objRandomThemes = JSON.parse(currentRandomThemes);
        if (objRandomThemes) {
          if (currentDate !== objRandomThemes.set_date) {
            shuffleThemes(currentRandomThemes.id);
          } else {
            setThemeUser(objRandomThemes);
          }
        } else {
          shuffleThemes();
        }
      }
      if (userThemes.id !== 6) {
        setThemeUser(userThemes);
      }
    };
    getThemes();
  }, [userThemes]);
  return getListTheme();
};
