import AsyncStorage from '@react-native-async-storage/async-storage';
import _ from 'lodash';
import moment from 'moment';
import {useEffect, useState} from 'react';

const theme1 = require('../assets/images/theme/1.png');
const theme2 = require('../assets/images/theme/2.png');
const theme3 = require('../assets/images/theme/3.png');
const theme4 = require('../assets/images/theme/4.png');
const theme5 = require('../assets/images/theme/5.png');
const theme6 = require('../assets/images/theme/6.png');
const theme7 = require('../assets/images/theme/7.png');
const theme8 = require('../assets/images/theme/8.png');
const theme9 = require('../assets/images/theme/9.png');
const theme10 = require('../assets/images/theme/10.png');
const theme11 = require('../assets/images/theme/11.png');
const theme12 = require('../assets/images/theme/12.png');
const theme13 = require('../assets/images/theme/13.png');
const theme14 = require('../assets/images/theme/14.png');
const theme15 = require('../assets/images/theme/15.png');
const theme16 = require('../assets/images/theme/16.png');
const theme17 = require('../assets/images/theme/17.png');
const theme18 = require('../assets/images/theme/18.png');
const theme19 = require('../assets/images/theme/19.png');
const theme20 = require('../assets/images/theme/20.png');
const theme21 = require('../assets/images/theme/21.png');
const theme22 = require('../assets/images/theme/22.png');
const theme23 = require('../assets/images/theme/23.png');
const theme24 = require('../assets/images/theme/24.png');
const theme25 = require('../assets/images/theme/25.png');
const theme26 = require('../assets/images/theme/26.png');
const theme27 = require('../assets/images/theme/27.png');
const theme28 = require('../assets/images/theme/28.png');
const theme29 = require('../assets/images/theme/29.png');
const theme30 = require('../assets/images/theme/30.png');
const theme31 = require('../assets/images/theme/31.png');
const theme32 = require('../assets/images/theme/32.png');
const theme33 = require('../assets/images/theme/33.png');
const theme34 = require('../assets/images/theme/34.png');
const theme35 = require('../assets/images/theme/35.png');
const theme36 = require('../assets/images/theme/36.png');
const theme37 = require('../assets/images/theme/37.png');
const theme38 = require('../assets/images/theme/38.png');
const theme39 = require('../assets/images/theme/39.png');
const theme40 = require('../assets/images/theme/40.png');
const theme41 = require('../assets/images/theme/abstract4.png');
const theme42 = require('../assets/images/theme/abstract5.png');
const theme43 = require('../assets/images/theme/illustration7.png');
const theme44 = require('../assets/images/theme/luxury04.png');
const theme45 = require('../assets/images/theme/luxury03.png');
const theme46 = require('../assets/images/theme/nature46.png');
const theme47 = require('../assets/images/theme/nature47.png');
const theme48 = require('../assets/images/theme/sunrisesunset48.png');
const theme49 = require('../assets/images/theme/texture49.png');
const theme50 = require('../assets/images/theme/texture50.png');

const theme51 = require('../assets/images/theme/51-abstract.png');
const theme52 = require('../assets/images/theme/52-abstract.png');
const theme53 = require('../assets/images/theme/53-calm.png');
const theme54 = require('../assets/images/theme/54-calm.png');
const theme55 = require('../assets/images/theme/55-illustration.png');
const theme56 = require('../assets/images/theme/56-illustration.png');
const theme57 = require('../assets/images/theme/57-luxury.png');
const theme58 = require('../assets/images/theme/58-luxury.png');
const theme59 = require('../assets/images/theme/59-nature.png');
const theme60 = require('../assets/images/theme/60-nature.png');
const theme61 = require('../assets/images/theme/61-nature.png');
const theme62 = require('../assets/images/theme/62-nature.png');
const theme63 = require('../assets/images/theme/63-nature.png');
const theme64 = require('../assets/images/theme/64-nature.png');
const theme65 = require('../assets/images/theme/65-nature.png');
const theme66 = require('../assets/images/theme/66-nature.png');
const theme67 = require('../assets/images/theme/67-seasonal.png');
const theme68 = require('../assets/images/theme/68-seasonal.png');
const theme69 = require('../assets/images/theme/69-seasonal.png');
const theme70 = require('../assets/images/theme/70-sunrise.png');

// Batch 17 May 2023
const theme71 = require('../assets/images/theme/71-calm.png');
const theme72 = require('../assets/images/theme/72-calm.png');
const theme73 = require('../assets/images/theme/73-calm.png');
const theme74 = require('../assets/images/theme/74-illustration.png');
const theme75 = require('../assets/images/theme/75-illustration.png');
const theme76 = require('../assets/images/theme/76-illustration.png');
const theme77 = require('../assets/images/theme/77-luxury.png');
const theme78 = require('../assets/images/theme/78-luxury.png');
const theme79 = require('../assets/images/theme/79-seasonal.png');
const theme80 = require('../assets/images/theme/80-textures.png');

// // Batch 24 Jun 2023
const theme81 = require('../assets/images/theme/81-Abstract.png');
const theme82 = require('../assets/images/theme/82-Abstract.png');
const theme83 = require('../assets/images/theme/83-Abstract.png');
const theme84 = require('../assets/images/theme/84-Calm.png');
const theme85 = require('../assets/images/theme/85-Illustration.png');
const theme86 = require('../assets/images/theme/87-Seasonal.png');
const theme87 = require('../assets/images/theme/87-Seasonal.png');
const theme88 = require('../assets/images/theme/88-sunrisesunset.png');
const theme89 = require('../assets/images/theme/89-sunrisesunset.png');
const theme90 = require('../assets/images/theme/90-textures.png');

export const listTheme = [
  {
    id: 1,
    entry_id: null,
    name: 'Theme 1',
    flag: null,
    is_free: 0,
    font_family: 'EBGaramond-Medium',
    font_size: 18,
    line_height: 24,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2022-11-17T08:35:00.000000Z',
    updated_at: null,
    imgLocal: theme1,
    background: {
      id: 17,
      owner_id: 1,
      type: 'theme',
      name: '1.png',
      created_at: '2022-11-17T08:35:00.000000Z',
      updated_at: null,
    },
  },
  {
    id: 2,
    entry_id: null,
    name: 'Theme 2',
    flag: null,
    is_free: 0,
    font_family: 'Koulen-Regular',
    font_size: 18,
    line_height: 24,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2022-11-17T08:35:00.000000Z',
    updated_at: null,
    imgLocal: theme2,
    background: {
      id: 18,
      owner_id: 2,
      type: 'theme',
      name: '2.png',
      created_at: '2022-11-17T08:35:00.000000Z',
      updated_at: null,
    },
  },
  {
    id: 3,
    entry_id: null,
    name: 'Theme 3',
    flag: null,
    is_free: 0,
    font_family: 'FjallaOne-Regular',
    font_size: 18,
    line_height: 24,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2022-11-17T08:35:00.000000Z',
    updated_at: null,
    imgLocal: theme3,
    background: {
      id: 19,
      owner_id: 3,
      type: 'theme',
      name: '3.png',
      created_at: '2022-11-17T08:35:00.000000Z',
      updated_at: null,
    },
  },
  {
    id: 4,
    entry_id: null,
    name: 'Theme 4',
    flag: null,
    is_free: 0,
    font_family: 'Montserrat-SemiBold',
    font_size: 18,
    line_height: 24,
    text_color: '#FFDA97',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2022-11-17T08:35:00.000000Z',
    updated_at: null,
    imgLocal: theme4,
    background: {
      id: 20,
      owner_id: 4,
      type: 'theme',
      name: '4.png',
      created_at: '2022-11-17T08:35:00.000000Z',
      updated_at: null,
    },
  },
  {
    id: 5,
    entry_id: null,
    name: 'Theme 5',
    flag: null,
    is_free: 0,
    font_family: 'PatuaOne-Regular',
    font_size: 18,
    line_height: 24,
    text_color: '#FFFFFF',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: 'rgba(0,0,0,0.7)',
    bg_image_color: null,
    status: 2,
    created_at: '2022-11-17T08:35:00.000000Z',
    updated_at: null,
    imgLocal: theme5,
    background: {
      id: 21,
      owner_id: 5,
      type: 'theme',
      name: '5.png',
      created_at: '2022-11-17T08:35:00.000000Z',
      updated_at: null,
    },
  },
  {
    id: 7,
    entry_id: null,
    name: 'Theme 7',
    flag: null,
    is_free: 0,
    font_family: 'Fondamento-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme7,
    background: {
      id: 57,
      owner_id: 7,
      type: 'theme',
      name: '7.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 8,
    entry_id: null,
    name: 'Theme 8',
    flag: null,
    is_free: 0,
    font_family: 'AnticDidone-Regular',
    font_size: 22,
    line_height: 32,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme8,
    background: {
      id: 58,
      owner_id: 8,
      type: 'theme',
      name: '8.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 9,
    entry_id: null,
    name: 'Theme 9',
    flag: null,
    is_free: 0,
    font_family: 'BethEllen-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme9,
    background: {
      id: 59,
      owner_id: 9,
      type: 'theme',
      name: '9.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 10,
    entry_id: null,
    name: 'Theme 10',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme10,
    background: {
      id: 60,
      owner_id: 10,
      type: 'theme',
      name: '10.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 11,
    entry_id: null,
    name: 'Theme 11',
    flag: null,
    is_free: 0,
    font_family: 'Fondamento-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme11,
    background: {
      id: 61,
      owner_id: 11,
      type: 'theme',
      name: '11.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 12,
    entry_id: null,
    name: 'Theme 12',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme12,
    background: {
      id: 62,
      owner_id: 12,
      type: 'theme',
      name: '12.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 13,
    entry_id: null,
    name: 'Theme 13',
    flag: null,
    is_free: 0,
    font_family: 'CarterOne',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme13,
    background: {
      id: 63,
      owner_id: 13,
      type: 'theme',
      name: '13.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 14,
    entry_id: null,
    name: 'Theme 14',
    flag: null,
    is_free: 0,
    font_family: 'Kreon-Regular',
    font_size: 22,
    line_height: 36,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: 'rgba(0, 0, 0, 0.5)',
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme14,
    background: {
      id: 64,
      owner_id: 14,
      type: 'theme',
      name: '14.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 15,
    entry_id: null,
    name: 'Theme 15',
    flag: null,
    is_free: 0,
    font_family: 'Caveat-Bold',
    font_size: 24,
    line_height: 30,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme15,
    background: {
      id: 65,
      owner_id: 15,
      type: 'theme',
      name: '15.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 16,
    entry_id: null,
    name: 'Theme 16',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme16,
    background: {
      id: 66,
      owner_id: 16,
      type: 'theme',
      name: '16.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 17,
    entry_id: null,
    name: 'Theme 17',
    flag: null,
    is_free: 0,
    font_family: 'DeliusSwashCaps-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme17,
    background: {
      id: 67,
      owner_id: 17,
      type: 'theme',
      name: '17.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 18,
    entry_id: null,
    name: 'Theme 18',
    flag: null,
    is_free: 0,
    font_family: 'Kreon-Regular',
    font_size: 22,
    line_height: 36,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: 'rgba(0, 0, 0, 0.5)',
    bg_image_color: null,
    status: 2,
    created_at: '2023-01-11T06:40:13.000000Z',
    updated_at: null,
    imgLocal: theme18,
    background: {
      id: 68,
      owner_id: 18,
      type: 'theme',
      name: '18.png',
      created_at: '2023-01-11T06:40:13.000000Z',
      updated_at: null,
    },
  },
  {
    id: 19,
    entry_id: null,
    name: 'Theme 19',
    flag: null,
    is_free: 0,
    font_family: 'Girassol-Regular',
    font_size: 24,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme19,
    background: {
      id: 69,
      owner_id: 19,
      type: 'theme',
      name: '19.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 20,
    entry_id: null,
    name: 'Theme 20',
    flag: null,
    is_free: 0,
    font_family: 'Gaegu-Regular',
    font_size: 26,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme20,
    background: {
      id: 70,
      owner_id: 20,
      type: 'theme',
      name: '20.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 21,
    entry_id: null,
    name: 'Theme 21',
    flag: null,
    is_free: 0,
    font_family: 'Farsan-Regular',
    font_size: 28,
    line_height: 39,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme21,
    background: {
      id: 71,
      owner_id: 21,
      type: 'theme',
      name: '21.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 22,
    entry_id: null,
    name: 'Theme 22',
    flag: null,
    is_free: 0,
    font_family: 'Hoefler Text Black',
    font_size: 26,
    line_height: 39,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme22,
    background: {
      id: 72,
      owner_id: 22,
      type: 'theme',
      name: '22.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 23,
    entry_id: null,
    name: 'Theme 23',
    flag: null,
    is_free: 0,
    font_family: 'IM FELL DW Pica',
    font_size: 26,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme23,
    background: {
      id: 73,
      owner_id: 23,
      type: 'theme',
      name: '23.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 24,
    entry_id: null,
    name: 'Theme 24',
    flag: null,
    is_free: 0,
    font_family: 'IbarraRealNova-Bold',
    font_size: 26,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme24,
    background: {
      id: 74,
      owner_id: 24,
      type: 'theme',
      name: '24.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 25,
    entry_id: null,
    name: 'Theme 25',
    flag: null,
    is_free: 0,
    font_family: 'Iceberg-Regular',
    font_size: 26,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme25,
    background: {
      id: 75,
      owner_id: 25,
      type: 'theme',
      name: '25.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 26,
    entry_id: null,
    name: 'Theme 26',
    flag: null,
    is_free: 0,
    font_family: 'PlayfairDisplay-Bold',
    font_size: 26,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme26,
    background: {
      id: 76,
      owner_id: 26,
      type: 'theme',
      name: '26.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 27,
    entry_id: null,
    name: 'Theme 27',
    flag: null,
    is_free: 0,
    font_family: 'Rowdies-Regular',
    font_size: 26,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme27,
    background: {
      id: 77,
      owner_id: 27,
      type: 'theme',
      name: '27.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 28,
    entry_id: null,
    name: 'Theme 28',
    flag: null,
    is_free: 0,
    font_family: 'Merienda-Bold',
    font_size: 24,
    line_height: 38,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme28,
    background: {
      id: 78,
      owner_id: 28,
      type: 'theme',
      name: '28.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 29,
    entry_id: null,
    name: 'Theme 29',
    flag: null,
    is_free: 0,
    font_family: 'Gloria Hallelujah',
    font_size: 24,
    line_height: 38,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme29,
    background: {
      id: 78,
      owner_id: 29,
      type: 'theme',
      name: '29.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 30,
    entry_id: null,
    name: 'Theme 30',
    flag: null,
    is_free: 0,
    font_family: 'Optima',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme30,
    background: {
      id: 78,
      owner_id: 30,
      type: 'theme',
      name: '30.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 31,
    entry_id: null,
    name: 'Theme 31',
    flag: null,
    is_free: 0,
    font_family: 'PalatinoLTPro-Medium',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme31,
    background: {
      id: 78,
      owner_id: 31,
      type: 'theme',
      name: '31.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 32,
    entry_id: null,
    name: 'Theme 32',
    flag: null,
    is_free: 0,
    font_family: 'Hoefler Text Black',
    font_size: 24,
    line_height: 39,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme32,
    background: {
      id: 78,
      owner_id: 32,
      type: 'theme',
      name: '32.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 33,
    entry_id: null,
    name: 'Theme 33',
    flag: null,
    is_free: 0,
    font_family: 'IM FELL DW Pica',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme33,
    background: {
      id: 78,
      owner_id: 33,
      type: 'theme',
      name: '33.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 34,
    entry_id: null,
    name: 'Theme 34',
    flag: null,
    is_free: 0,
    font_family: 'PalatinoLTPro-Medium',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme34,
    background: {
      id: 78,
      owner_id: 34,
      type: 'theme',
      name: '34.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 35,
    entry_id: null,
    name: 'Theme 35',
    flag: null,
    is_free: 0,
    font_family: 'AnticDidone-Regular',
    font_size: 22,
    line_height: 36,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme35,
    background: {
      id: 78,
      owner_id: 35,
      type: 'theme',
      name: '34.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 36,
    entry_id: null,
    name: 'Theme 36',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 22,
    line_height: 36,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme36,
    background: {
      id: 78,
      owner_id: 36,
      type: 'theme',
      name: '36.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 37,
    entry_id: null,
    name: 'Theme 37',
    flag: null,
    is_free: 0,
    font_family: 'Capriola-Regular',
    font_size: 22,
    line_height: 38,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme37,
    background: {
      id: 78,
      owner_id: 37,
      type: 'theme',
      name: '37.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 38,
    entry_id: null,
    name: 'Theme 38',
    flag: null,
    is_free: 0,
    font_family: 'AnticDidone-Regular',
    font_size: 22,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme38,
    background: {
      id: 78,
      owner_id: 38,
      type: 'theme',
      name: '38.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 39,
    entry_id: null,
    name: 'Theme 39',
    flag: null,
    is_free: 0,
    font_family: 'AnticDidone-Regular',
    font_size: 22,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme39,
    background: {
      id: 78,
      owner_id: 39,
      type: 'theme',
      name: '39.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    id: 40,
    entry_id: null,
    name: 'Theme 40',
    flag: null,
    is_free: 0,
    font_family: 'Gaegu-Regular',
    font_size: 26,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-02-03T14:17:03.000000Z',
    updated_at: null,
    imgLocal: theme40,
    background: {
      id: 70,
      owner_id: 40,
      type: 'theme',
      name: '40.png',
      created_at: '2023-02-03T14:17:03.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme41,
    id: 41,
    entry_id: null,
    group_id: 8,
    name: 'Theme 41',
    flag: null,
    is_free: 0,
    font_family: 'PalatinoLTPro-Medium',
    font_size: 24,
    line_height: 38,
    text_color: '#F0CD96',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-15T02:51:51.000000Z',
    updated_at: null,
    background: {
      id: 92,
      owner_id: 41,
      type: 'theme',
      name: '41.png',
      url: '/assets/images/theme/bg/41.png',
      created_at: '2023-03-15T02:51:51.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme42,
    id: 42,
    entry_id: null,
    group_id: 8,
    name: 'Theme 42',
    flag: null,
    is_free: 0,
    font_family: 'Montserrat-SemiBold',
    font_size: 18,
    line_height: 24,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-15T02:51:51.000000Z',
    updated_at: null,
    background: {
      id: 93,
      owner_id: 42,
      type: 'theme',
      name: '42.png',
      url: '/assets/images/theme/bg/42.png',
      created_at: '2023-03-15T02:51:51.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme43,
    id: 43,
    entry_id: null,
    group_id: 10,
    name: 'Theme 43',
    flag: null,
    is_free: 0,
    font_family: 'Rowdies-Regular',
    font_size: 26,
    line_height: 38,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-15T02:51:51.000000Z',
    updated_at: null,
    background: {
      id: 94,
      owner_id: 43,
      type: 'theme',
      name: '43.png',
      url: '/assets/images/theme/bg/43.png',
      created_at: '2023-03-15T02:51:51.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme44,
    id: 44,
    entry_id: null,
    group_id: 11,
    name: 'Theme 44',
    flag: null,
    is_free: 0,
    font_family: 'Optima',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-15T02:51:51.000000Z',
    updated_at: null,
    background: {
      id: 95,
      owner_id: 44,
      type: 'theme',
      name: '44.png',
      url: '/assets/images/theme/bg/44.png',
      created_at: '2023-03-15T02:51:51.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme45,
    id: 45,
    entry_id: null,
    group_id: 11,
    name: 'Theme 45',
    flag: null,
    is_free: 0,
    font_family: 'Optima',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-15T02:51:51.000000Z',
    updated_at: null,
    background: {
      id: 96,
      owner_id: 45,
      type: 'theme',
      name: '45.png',
      url: '/assets/images/theme/bg/45.png',
      created_at: '2023-03-15T02:51:51.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme46,
    id: 46,
    entry_id: null,
    group_id: 13,
    name: 'Theme 46',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#631F1F',
    text_shadow: null,
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-15T02:51:51.000000Z',
    updated_at: null,
    background: {
      id: 97,
      owner_id: 46,
      type: 'theme',
      name: '46.png',
      url: '/assets/images/theme/bg/46.png',
      created_at: '2023-03-15T02:51:51.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme47,
    id: 47,
    entry_id: null,
    group_id: 13,
    name: 'Theme 47',
    flag: null,
    is_free: 0,
    font_family: 'FjallaOne-Regular',
    font_size: 18,
    line_height: 24,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-15T02:51:51.000000Z',
    updated_at: null,
    background: {
      id: 98,
      owner_id: 47,
      type: 'theme',
      name: '47.png',
      url: '/assets/images/theme/bg/47.png',
      created_at: '2023-03-15T02:51:51.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme48,
    id: 48,
    entry_id: null,
    group_id: 14,
    name: 'Theme 48',
    flag: null,
    is_free: 0,
    font_family: 'Montserrat-SemiBold',
    font_size: 18,
    line_height: 24,
    text_color: '#000',
    text_shadow: null,
    text_shadow_offset: '',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-15T02:51:51.000000Z',
    updated_at: null,
    background: {
      id: 99,
      owner_id: 48,
      type: 'theme',
      name: '48.png',
      url: '/assets/images/theme/bg/48.png',
      created_at: '2023-03-15T02:51:51.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme49,
    id: 49,
    entry_id: null,
    group_id: 15,
    name: 'Theme 49',
    flag: null,
    is_free: 0,
    font_family: 'Rowdies-Regular',
    font_size: 26,
    line_height: 38,
    text_color: '#FADAC3',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-15T02:51:51.000000Z',
    updated_at: null,
    background: {
      id: 100,
      owner_id: 49,
      type: 'theme',
      name: '49.png',
      url: '/assets/images/theme/bg/49.png',
      created_at: '2023-03-15T02:51:51.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme50,
    id: 50,
    entry_id: null,
    group_id: 15,
    name: 'Theme 50',
    flag: null,
    is_free: 0,
    font_family: 'Koulen-Regular',
    font_size: 18,
    line_height: 24,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-15T02:51:51.000000Z',
    updated_at: null,
    background: {
      id: 101,
      owner_id: 50,
      type: 'theme',
      name: '50.png',
      url: '/assets/images/theme/bg/50.png',
      created_at: '2023-03-15T02:51:51.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme51,
    id: 51,
    entry_id: null,
    group_id: 8,
    name: 'Theme 51',
    flag: null,
    is_free: 0,
    font_family: 'Hoefler Text Black',
    font_size: 26,
    line_height: 39,
    text_color: '#473883',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 102,
      owner_id: 51,
      type: 'theme',
      name: '51.png',
      url: '/assets/images/theme/bg/51.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 52,
    imgLocal: theme52,
    entry_id: null,
    group_id: 8,
    name: 'Theme 52',
    flag: null,
    is_free: 0,
    font_family: 'Fondamento-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 103,
      owner_id: 52,
      type: 'theme',
      name: '52.png',
      url: '/assets/images/theme/bg/52.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 53,
    imgLocal: theme53,
    entry_id: null,
    group_id: 9,
    name: 'Theme 53',
    flag: null,
    is_free: 0,
    font_family: 'Fondamento-Regular',
    font_size: 24,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 104,
      owner_id: 53,
      type: 'theme',
      name: '53.png',
      url: '/assets/images/theme/bg/53.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 54,
    imgLocal: theme54,
    entry_id: null,
    group_id: 9,
    name: 'Theme 54',
    flag: null,
    is_free: 0,
    font_family: 'Caveat-Bold',
    font_size: 24,
    line_height: 30,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 105,
      owner_id: 54,
      type: 'theme',
      name: '54.png',
      url: '/assets/images/theme/bg/54.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 55,
    imgLocal: theme55,
    entry_id: null,
    group_id: 10,
    name: 'Theme 55',
    flag: null,
    is_free: 0,
    font_family: 'DeliusSwashCaps-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 106,
      owner_id: 55,
      type: 'theme',
      name: '55.png',
      url: '/assets/images/theme/bg/55.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 56,
    imgLocal: theme56,
    entry_id: null,
    group_id: 10,
    name: 'Theme 55',
    flag: null,
    is_free: 0,
    font_family: 'Montserrat-Bold',
    font_size: 20,
    line_height: 28,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":4,"height":4}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 106,
      owner_id: 55,
      type: 'theme',
      name: '55.png',
      url: '/assets/images/theme/bg/55.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 57,
    imgLocal: theme57,
    entry_id: null,
    group_id: 11,
    name: 'Theme 57',
    flag: null,
    is_free: 0,
    font_family: 'Fondamento-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 108,
      owner_id: 57,
      type: 'theme',
      name: '57.png',
      url: '/assets/images/theme/bg/57.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 58,
    imgLocal: theme58,
    entry_id: null,
    group_id: 11,
    name: 'Theme 58',
    flag: null,
    is_free: 0,
    font_family: 'Hoefler Text Black',
    font_size: 26,
    line_height: 39,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 109,
      owner_id: 58,
      type: 'theme',
      name: '58.png',
      url: '/assets/images/theme/bg/58.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 59,
    imgLocal: theme59,
    entry_id: null,
    group_id: 12,
    name: 'Theme 59',
    flag: null,
    is_free: 0,
    font_family: 'IM FELL DW Pica',
    font_size: 26,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 110,
      owner_id: 59,
      type: 'theme',
      name: '59.png',
      url: '/assets/images/theme/bg/59.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme60,
    id: 60,
    entry_id: null,
    group_id: 12,
    name: 'Theme 60',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 111,
      owner_id: 60,
      type: 'theme',
      name: '60.png',
      url: '/assets/images/theme/bg/60.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme61,
    id: 61,
    entry_id: null,
    group_id: 12,
    name: 'Theme 61',
    flag: null,
    is_free: 0,
    font_family: 'Optima',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 112,
      owner_id: 61,
      type: 'theme',
      name: '61.png',
      url: '/assets/images/theme/bg/61.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme62,
    id: 62,
    entry_id: null,
    group_id: 12,
    name: 'Theme 62',
    flag: null,
    is_free: 0,
    font_family: 'Merienda-Bold',
    font_size: 24,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 113,
      owner_id: 62,
      type: 'theme',
      name: '62.png',
      url: '/assets/images/theme/bg/62.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme63,
    id: 63,
    entry_id: null,
    group_id: 12,
    name: 'Theme 63',
    flag: null,
    is_free: 0,
    font_family: 'FjallaOne-Regular',
    font_size: 22,
    line_height: 32,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 114,
      owner_id: 63,
      type: 'theme',
      name: '63.png',
      url: '/assets/images/theme/bg/63.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: theme64,
    id: 64,
    entry_id: null,
    group_id: 12,
    name: 'Theme 64',
    flag: null,
    is_free: 0,
    font_family: 'Montserrat-SemiBold',
    font_size: 20,
    line_height: 32,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":4,"height":4}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 115,
      owner_id: 64,
      type: 'theme',
      name: '64.png',
      url: '/assets/images/theme/bg/64.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 65,
    imgLocal: theme65,
    entry_id: null,
    group_id: 12,
    name: 'Theme 65',
    flag: null,
    is_free: 0,
    font_family: 'FjallaOne-Regular',
    font_size: 22,
    line_height: 32,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 116,
      owner_id: 65,
      type: 'theme',
      name: '65.png',
      url: '/assets/images/theme/bg/65.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 66,
    imgLocal: theme66,
    entry_id: null,
    group_id: 12,
    name: 'Theme 66',
    flag: null,
    is_free: 0,
    font_family: 'Hoefler Text Black',
    font_size: 26,
    line_height: 39,
    text_color: '#473883',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 117,
      owner_id: 66,
      type: 'theme',
      name: '66.png',
      url: '/assets/images/theme/bg/66.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 67,
    imgLocal: theme67,
    entry_id: null,
    group_id: 13,
    name: 'Theme 67',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 118,
      owner_id: 67,
      type: 'theme',
      name: '67.png',
      url: '/assets/images/theme/bg/67.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 68,
    imgLocal: theme68,
    entry_id: null,
    group_id: 13,
    name: 'Theme 68',
    flag: null,
    is_free: 0,
    font_family: 'Optima',
    font_size: 24,
    line_height: 38,
    text_color: '#0E1E74',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 119,
      owner_id: 68,
      type: 'theme',
      name: '68.png',
      url: '/assets/images/theme/bg/68.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 69,
    imgLocal: theme69,
    entry_id: null,
    group_id: 13,
    name: 'Theme 69',
    flag: null,
    is_free: 0,
    font_family: 'IM FELL DW Pica',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 120,
      owner_id: 69,
      type: 'theme',
      name: '69.png',
      url: '/assets/images/theme/bg/69.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 70,
    imgLocal: theme70,
    entry_id: null,
    group_id: 14,
    name: 'Theme 70',
    flag: null,
    is_free: 0,
    font_family: 'Optima-ExtraBlack',
    font_size: 24,
    line_height: 34,
    text_color: '#5F0A01',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-04-04T06:54:45.000000Z',
    updated_at: null,
    background: {
      id: 121,
      owner_id: 70,
      type: 'theme',
      name: '70.png',
      url: '/assets/images/theme/bg/70.png',
      created_at: '2023-04-04T06:54:45.000000Z',
      updated_at: null,
    },
  },
  {
    id: 71,
    imgLocal: theme71,
    entry_id: null,
    group_id: 9,
    name: 'Theme 71',
    flag: null,
    is_free: 0,
    font_family: 'PalatinoLTPro-Medium',
    font_size: 24,
    line_height: 38,
    text_color: '#FFFFFF',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-05-12T02:02:41.000000Z',
    updated_at: null,
    background: {
      id: 122,
      owner_id: 71,
      type: 'theme',
      name: '71.png',
      url: '/assets/images/theme/bg/71.png',
      created_at: '2023-05-12T02:02:41.000000Z',
      updated_at: null,
    },
  },
  {
    id: 72,
    imgLocal: theme72,
    entry_id: null,
    group_id: 9,
    name: 'Theme 72',
    flag: null,
    is_free: 0,
    font_family: 'Hoefler Text Black',
    font_size: 26,
    line_height: 39,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-05-12T02:02:41.000000Z',
    updated_at: null,
    background: {
      id: 123,
      owner_id: 72,
      type: 'theme',
      name: '72.png',
      url: '/assets/images/theme/bg/72.png',
      created_at: '2023-05-12T02:02:41.000000Z',
      updated_at: null,
    },
  },
  {
    id: 73,
    imgLocal: theme73,
    entry_id: null,
    group_id: 9,
    name: 'Theme 73',
    flag: null,
    is_free: 0,
    font_family: 'Caveat-Bold',
    font_size: 24,
    line_height: 30,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-05-12T02:02:41.000000Z',
    updated_at: null,
    background: {
      id: 124,
      owner_id: 73,
      type: 'theme',
      name: '73.png',
      url: '/assets/images/theme/bg/73.png',
      created_at: '2023-05-12T02:02:41.000000Z',
      updated_at: null,
    },
  },

  {
    id: 74,
    imgLocal: theme74,
    entry_id: null,
    group_id: 10,
    name: 'Theme 74',
    flag: null,
    is_free: 0,
    font_family: 'Fondamento-Regular',
    font_size: 24,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-05-12T02:02:41.000000Z',
    updated_at: null,
    background: {
      id: 125,
      owner_id: 74,
      type: 'theme',
      name: '74.png',
      url: '/assets/images/theme/bg/74.png',
      created_at: '2023-05-12T02:02:41.000000Z',
      updated_at: null,
    },
  },
  {
    id: 75,
    imgLocal: theme75,
    entry_id: null,
    group_id: 10,
    name: 'Theme 75',
    flag: null,
    is_free: 0,
    font_family: 'DeliusSwashCaps-Regular',
    font_size: 22,
    line_height: 34,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-05-12T02:02:41.000000Z',
    updated_at: null,
    background: {
      id: 126,
      owner_id: 75,
      type: 'theme',
      name: '75.png',
      url: '/assets/images/theme/bg/75.png',
      created_at: '2023-05-12T02:02:41.000000Z',
      updated_at: null,
    },
  },
  {
    id: 76,
    imgLocal: theme76,
    entry_id: null,
    group_id: 10,
    name: 'Theme 76',
    flag: null,
    is_free: 0,
    font_family: 'PlayfairDisplay-Bold',
    font_size: 24,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-05-12T02:02:41.000000Z',
    updated_at: null,
    background: {
      id: 127,
      owner_id: 76,
      type: 'theme',
      name: '76.png',
      url: '/assets/images/theme/bg/76.png',
      created_at: '2023-05-12T02:02:41.000000Z',
      updated_at: null,
    },
  },
  {
    id: 77,
    imgLocal: theme77,
    entry_id: null,
    group_id: 11,
    name: 'Theme 77',
    flag: null,
    is_free: 0,
    font_family: 'FjallaOne-Regular',
    font_size: 20,
    line_height: 36,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-05-12T02:02:41.000000Z',
    updated_at: null,
    background: {
      id: 128,
      owner_id: 77,
      type: 'theme',
      name: '77.png',
      url: '/assets/images/theme/bg/77.png',
      created_at: '2023-05-12T02:02:41.000000Z',
      updated_at: null,
    },
  },
  {
    id: 78,
    imgLocal: theme78,
    entry_id: null,
    group_id: 11,
    name: 'Theme 78',
    flag: null,
    is_free: 0,
    font_family: 'AnticDidone-Regular',
    font_size: 22,
    line_height: 32,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-05-12T02:02:41.000000Z',
    updated_at: null,
    background: {
      id: 129,
      owner_id: 78,
      type: 'theme',
      name: '78.png',
      url: '/assets/images/theme/bg/78.png',
      created_at: '2023-05-12T02:02:41.000000Z',
      updated_at: null,
    },
  },
  {
    id: 79,
    imgLocal: theme79,
    entry_id: null,
    group_id: 13,
    name: 'Theme 79',
    flag: null,
    is_free: 0,
    font_family: 'Merienda-Bold',
    font_size: 24,
    line_height: 38,
    text_color: '#FFF8AA',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-05-12T02:02:41.000000Z',
    updated_at: null,
    background: {
      id: 130,
      owner_id: 79,
      type: 'theme',
      name: '79.png',
      url: '/assets/images/theme/bg/79.png',
      created_at: '2023-05-12T02:02:41.000000Z',
      updated_at: null,
    },
  },
  {
    id: 80,
    entry_id: null,
    imgLocal: theme80,
    group_id: 15,
    name: 'Theme 80',
    flag: null,
    is_free: 0,
    font_family: 'Koulen-Regular',
    font_size: 24,
    line_height: 36,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":2,"height":2}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-05-12T02:02:41.000000Z',
    updated_at: null,
    background: {
      id: 131,
      owner_id: 80,
      type: 'theme',
      name: '80.png',
      url: '/assets/images/theme/bg/80.png',
      created_at: '2023-05-12T02:02:41.000000Z',
      updated_at: null,
    },
  },
  {
    id: 81,
    entry_id: null,
    imgLocal: theme81,
    group_id: 8,
    name: 'Theme 81',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 24,
    line_height: 32,
    text_color: '#BA0808',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-06-02T02:54:27.000000Z',
    updated_at: null,
    background: {
      id: 132,
      owner_id: 81,
      type: 'theme',
      name: '81.png',
      url: '/assets/images/theme/bg/81.png',
      created_at: '2023-06-02T02:54:27.000000Z',
      updated_at: null,
    },
  },
  {
    id: 82,
    entry_id: null,
    imgLocal: theme82,
    group_id: 8,
    name: 'Theme 82',
    flag: null,
    is_free: 0,
    font_family: 'Montserrat-SemiBold',
    font_size: 24,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-06-02T02:54:27.000000Z',
    updated_at: null,
    background: {
      id: 133,
      owner_id: 82,
      type: 'theme',
      name: '82.png',
      url: '/assets/images/theme/bg/82.png',
      created_at: '2023-06-02T02:54:27.000000Z',
      updated_at: null,
    },
  },
  {
    id: 83,
    entry_id: null,
    imgLocal: theme83,
    group_id: 8,
    name: 'Theme 83',
    flag: null,
    is_free: 0,
    font_family: 'Calistoga-Regular',
    font_size: 24,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-06-02T02:54:27.000000Z',
    updated_at: null,
    background: {
      id: 134,
      owner_id: 83,
      type: 'theme',
      name: '83.png',
      url: '/assets/images/theme/bg/83.png',
      created_at: '2023-06-02T02:54:27.000000Z',
      updated_at: null,
    },
  },
  {
    id: 84,
    entry_id: null,
    imgLocal: theme84,
    group_id: 9,
    name: 'Theme 84',
    flag: null,
    is_free: 0,
    font_family: 'Merienda-Bold',
    font_size: 24,
    line_height: 34,
    text_color: '#1E527D',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-06-02T02:54:27.000000Z',
    updated_at: null,
    background: {
      id: 135,
      owner_id: 84,
      type: 'theme',
      name: '84.png',
      url: '/assets/images/theme/bg/84.png',
      created_at: '2023-06-02T02:54:27.000000Z',
      updated_at: null,
    },
  },
  {
    id: 85,
    entry_id: null,
    imgLocal: theme85,
    group_id: 10,
    name: 'Theme 85',
    flag: null,
    is_free: 0,
    font_family: 'Libre Baskerville',
    font_size: 24,
    line_height: 34,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-06-02T02:54:27.000000Z',
    updated_at: null,
    background: {
      id: 136,
      owner_id: 85,
      type: 'theme',
      name: '85.png',
      url: '/assets/images/theme/bg/85.png',
      created_at: '2023-06-02T02:54:27.000000Z',
      updated_at: null,
    },
  },
  {
    id: 86,
    entry_id: null,
    imgLocal: theme86,
    group_id: 13,
    name: 'Theme 86',
    flag: null,
    is_free: 0,
    font_family: 'FjallaOne-Regular',
    font_size: 24,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-06-02T02:54:27.000000Z',
    updated_at: null,
    background: {
      id: 137,
      owner_id: 86,
      type: 'theme',
      name: '86.png',
      url: '/assets/images/theme/bg/86.png',
      created_at: '2023-06-02T02:54:27.000000Z',
      updated_at: null,
    },
  },
  {
    id: 87,
    entry_id: null,
    imgLocal: theme87,
    group_id: 13,
    name: 'Theme 87',
    flag: null,
    is_free: 0,
    font_family: 'Gaegu-Regular',
    font_size: 24,
    line_height: 34,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-06-02T02:54:27.000000Z',
    updated_at: null,
    background: {
      id: 138,
      owner_id: 87,
      type: 'theme',
      name: '87.png',
      url: '/assets/images/theme/bg/87.png',
      created_at: '2023-06-02T02:54:27.000000Z',
      updated_at: null,
    },
  },
  {
    id: 88,
    entry_id: null,
    imgLocal: theme88,
    group_id: 14,
    name: 'Theme 88',
    flag: null,
    is_free: 0,
    font_family: 'Optima',
    font_size: 24,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-06-02T02:54:27.000000Z',
    updated_at: null,
    background: {
      id: 139,
      owner_id: 88,
      type: 'theme',
      name: '88.png',
      url: '/assets/images/theme/bg/88.png',
      created_at: '2023-06-02T02:54:27.000000Z',
      updated_at: null,
    },
  },
  {
    id: 89,
    entry_id: null,
    imgLocal: theme89,
    group_id: 14,
    name: 'Theme 89',
    flag: null,
    is_free: 0,
    font_family: 'Koulen-Regular',
    font_size: 24,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-06-02T02:54:27.000000Z',
    updated_at: null,
    background: {
      id: 140,
      owner_id: 89,
      type: 'theme',
      name: '89.png',
      url: '/assets/images/theme/bg/89.png',
      created_at: '2023-06-02T02:54:27.000000Z',
      updated_at: null,
    },
  },
  {
    id: 90,
    entry_id: null,
    imgLocal: theme90,
    group_id: 15,
    name: 'Theme 90',
    flag: null,
    is_free: 0,
    font_family: 'FjallaOne-Regular',
    font_size: 24,
    line_height: 34,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 1,
    created_at: '2023-06-09T01:14:28.000000Z',
    updated_at: null,
    background: {
      id: 140,
      owner_id: 90,
      type: 'theme',
      name: '90.png',
      url: '/assets/images/theme/bg/90.png',
      created_at: '2023-06-09T01:14:28.000000Z',
      updated_at: null,
    },
  },
];

export const handleShuffleTheme = async () => {
  const getItems = listTheme[Math.floor(Math.random() * listTheme.length)];
  const updateObj = {
    ...getItems,
    set_date: moment().format('YYYY-MM-DD'),
  };
  return updateObj;
};

export const useBackgroundQuotes = userThemes => {
  const [themeUser, setThemeUser] = useState(userThemes);

  const shuffleThemes = async themeId => {
    const filterThemes = themeId
      ? listTheme.filter(item => item.id !== themeId)
      : listTheme;
    const getItems =
      filterThemes[Math.floor(Math.random() * filterThemes.length)];
    const updateObj = {
      ...getItems,
      set_date: moment().format('YYYY-MM-DD'),
    };
    const objString = JSON.stringify(updateObj);
    setThemeUser(getItems);
    await AsyncStorage.setItem('randomThemes', objString);
  };

  // console.log('User theme :', themeUser);
  // console.log('User userThemes :', userThemes);

  const getListTheme = () => {
    if (themeUser && themeUser?.id) {
      const findTheme = listTheme.find(item => item.id === themeUser.id);
      if (findTheme) {
        return [findTheme];
      }
    }
    return [userThemes];
  };

  useEffect(() => {
    const getThemes = async () => {
      if (userThemes.id === 6) {
        const currentDate = moment().format('YYYY-MM-DD');
        const currentRandomThemes = await AsyncStorage.getItem('randomThemes');
        const objRandomThemes = JSON.parse(currentRandomThemes);
        if (objRandomThemes) {
          if (currentDate !== objRandomThemes.set_date) {
            shuffleThemes(currentRandomThemes.id);
          } else {
            setThemeUser(objRandomThemes);
          }
        } else {
          shuffleThemes();
        }
      }
      if (userThemes.id !== 6) {
        setThemeUser(userThemes);
      }
    };
    getThemes();
  }, [userThemes]);
  return getListTheme();
};
